permalink: /:categories/:title/
exclude:
  - README.wiki
  - Capfile
  - config

url: http://eq19.github.io
name: The ₠Quantum Project
topic: Networking
path: /world/net

disqus_shortname: tophyips
google_analytics: UA-79558814-1
